server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到eureka server，默认true
    fetch-registry: false #是否从eureka server获取注册信息，默认true
    service-url:
      delfaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #服务注册的URL